### ISSUE TITLE
Contribute to Flycheck

### ISSUE THREAD

**Issue by swsnr** [lbolla/emacs-flycheck-mypy#1]
Would you like to contribute this syntax checker to Flycheck itself?

**Comment by hujianxin** [comment]
Yes! It's great, can you contribute this checker to flycheck?

**Comment by lbolla** [comment]
I have not done this before because I thought that mypy is a pretty specific checker, under active development, that is served best by an external flycheck plugin. What is the reason to include it in the main flycheck distribution?

**Comment by hujianxin** [comment]
Mabey I can use both flycheck-flake8 and flycheck-mypy in python major mode. But I don't know whether it is useful or not.

**Comment by lbolla** [comment]
@hujianxin I am not sure I understand your comment. Surely you can (I do in fact), but either case that has nothing to do with flycheck-mypy being part of the main flycheck package or not. You can always install the flycheck-mypy package from melpa if you want it.

**Comment by hujianxin** [comment]
@lbolla Thanks a lot, I understand your meaning.

**Comment by unhammer** [comment]
@lbolla to me it makes sense; flycheck already includes lots of fairly "specific" checkers (e.g. cppcheck), and it improves the out-of-the-box experience. It doesn't run the checker if it's not installed, anyway.

**Comment by Wilfred** [comment]
@lbolla I'd love to see this checker in flycheck itself. It helps discovery for new users.

There are lots of very specific checkers in flycheck already. Would you be happy with contributing this to flycheck, or me doing so?

**Comment by lbolla** [comment]
@Wilfred Sure, feel free to include it to the standard flycheck distribution!
Let me know if I can help.

**Comment by cpitclaudel** [comment]
We have mypy in Flycheck now; do you want to continue development there? I think we've diverged since the code was merged (with the addition of the `:working-directory` property on your side; maybe we should reflect that in flycheck itself?

**Comment by lbolla** [comment]
@cpitclaudel Sure, shall I submit a PR to flycheck with the `:working-directory` patch?
It may be worth deprecating this library altogether now that it's merged on flycheck.

**Comment by cpitclaudel** [comment]
I think deprecating this library sounds good.  

> Sure, shall I submit a PR to flycheck with the :working-directory patch?

Sounds good, but even better you could join the discussion at https://github.com/flycheck/flycheck/issues/1711
